### PR TITLE
Update purs (0.15.11)

### PR DESCRIPTION
**Pull request by robo-trh**
Update purs (0.15.11)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Not merging because the Linux release asset is missing. See: https://github.com/purescript/purescript/issues/4486

Once the release is updated the daily updater can be re-run.

**Comment by JordanMartinez** [comment]
Release asset has been added.

**Comment by JordanMartinez** [comment]
Actually, the release artifact wasn't built properly. I'm fixing that now.

**Comment by JordanMartinez** [comment]
K, release artifact has been fixed.

**Comment by thomashoneyman** [comment]
See https://github.com/thomashoneyman/purescript-overlay/pull/50

**Pull request closed without merging**
